// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Linq;
using KSP;
using UnityEngine;

namespace AnimatedDecouplers
{
	public class ModuleAnimatedAnchoredDecoupler : ModuleAnchoredDecoupler
	{
		[KSPField]
		public string animationName;
		
		protected Animation anim;
		
		[KSPField(isPersistant = true)]
		public bool animationComplete;
		
		public ModuleAnimatedAnchoredDecoupler ():
		base()
		{
		}

		public override void OnStart (StartState state)
		{
			Debug.Log ("ModuleAnimatedAnchoredDecoupler.OnStart(), isDecoupled = " + isDecoupled.ToString ());
			anim = part.FindModelAnimators(animationName).FirstOrDefault ();
			if ((object)anim == null)
			{
				Debug.Log ("ModuleAnimatedAnchoredDecoupler: Animations not found");
			}
			else
			{
				if (animationComplete)
				{
					anim[animationName].normalizedTime = 1f;
				}
				GameEvents.onStageSeparation.Add (checkForDecoupling);
			}
			base.OnStart (state);
		}

		public void checkForDecoupling(EventReport separationData)
		{
			if (separationData.eventType == FlightEvents.STAGESEPARATION && separationData.origin == this.part)
			{
				// PROBABLY got called because we decoupled, but no way to know because ModuleAnchoredDecoupler doesn't SET isDecoupled until after the event fires. 
				if (!this.animationComplete || !this.anim.IsPlaying (animationName))
				{
					this.anim.Play (animationName);
					print ("ModuleAnimatedDecoupler.onStageSeparation() triggered animation " + this.animationName);
				}
			}
		}


		public override void OnActive()
		{
			Debug.Log ("ModuleAnimatedAnchoredDecoupler.OnActive() start; isDecoupled = " + this.isDecoupled.ToString ());
			//base.OnActive ();
			//if (this.isDecoupled && (object)anims != null && !animationComplete) 
			if ((object)anim != null && !this.animationComplete) 
			{
				try
				{
					this.anim.Play (animationName);
					animationComplete = true;
				}
				catch (Exception e)
				{
					Debug.Log ("ModuleAnimatedAnchoredDecoupler error! " + e.Message);
				}
			}
			base.OnActive ();
			Debug.Log ("ModuleAnimatedAnchoredDecoupler.OnActive() finished; isDecoupled = " + this.isDecoupled.ToString ());
		}
	}
}

